require 'bundler'
Bundler.require
require_all 'lib'
require 'pry'

require_relative '../lib/appointment.rb'
require_relative '../lib/artist.rb'
require_relative '../lib/doctor.rb'
require_relative '../lib/genre.rb'
require_relative '../lib/patient.rb'
require_relative '../lib/song.rb'
# require_relative '.../spec/artist_spec.rb'
# require_relative '.../spec/song_spec.rb'
# require_relative '.../spec/genre_spec.rb'
# require_relative '.../spec/doctor_spec.rb'
# require_relative '.../spec/appointment_spec.rb'
# require_relative '.../spec/patient_spec.rb'